# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Backend/Mango.Services.AuthAPI/Mango.Services.AuthAPI.csproj", "Backend/Mango.Services.AuthAPI/"]
COPY ["Integration/Mango.MessageBus/Mango.MessageBus.csproj", "Integration/Mango.MessageBus/"]
RUN dotnet restore "Backend/Mango.Services.AuthAPI/Mango.Services.AuthAPI.csproj"
COPY . .
WORKDIR "/src/Backend/Mango.Services.AuthAPI"
RUN dotnet build "Mango.Services.AuthAPI.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Mango.Services.AuthAPI.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:8080
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Mango.Services.AuthAPI.dll"]