name: AuthAPI CI

on:
  push:
    branches:
      - main
      - feature/hanna
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      # Authenticate normal .NET restore to GitHub Packages
      - name: Add GitHub Packages source
        run: |
          dotnet nuget add source \
            --username "${{ github.actor }}" \
            --password "${{ secrets.GH_PACKAGES_TOKEN }}" \
            --store-password-in-clear-text \
            --name github \
            "https://nuget.pkg.github.com/MdKasimS-CCG/index.json"

      - name: Restore dependencies
        run: dotnet restore Mango.Services.AuthAPI.csproj

      - name: Build
        run: dotnet build Mango.Services.AuthAPI.csproj --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release

      # Create temporary NuGet config for Docker
      - name: Create NuGet config
        run: |
          dotnet nuget add source \
            --username "${{ github.actor }}" \
            --password "${{ secrets.GH_PACKAGES_TOKEN }}" \
            --store-password-in-clear-text \
            --name github \
            "https://nuget.pkg.github.com/MdKasimS-CCG/index.json" \
            --configfile ./NuGet.Config

      # Build Docker image using NuGet config as a BuildKit secret
      - name: Build Docker image
        run: |
          docker build \
            --secret id=nuget_config,src=./NuGet.Config \
            -t mango-authapi:latest .

      # Remove temporary credentials file
      - name: Remove NuGet config
        if: always()
        run: rm -f ./NuGet.Config